null_response: 'Tried parsing null or empty response'
ai_response_format: 'AI response did not match the desired problem/skill format'
db_run_time: 'Database connection failed'
db_set_up_exists: 'Database setup file is missing or corrupted'
